# Generated by Django 5.2 on 2025-05-13 15:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
                ('specialization', models.CharField(default='General', max_length=100)),
                ('jurisdiction_level', models.CharField(choices=[('National', 'National'), ('Governorate', 'Governorate'), ('District', 'District')], default='District', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('full_name', models.CharField(default='', max_length=200)),
                ('specialization', models.CharField(default='General', max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('office_name', models.CharField(default='', max_length=200)),
                ('office_address', models.TextField(default='')),
                ('fax_no', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='lawyer@example.com', max_length=254, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('location', models.CharField(default='', max_length=100)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('bar_association_id', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name_ar', models.CharField(max_length=100)),
                ('last_name_ar', models.CharField(max_length=100)),
                ('first_name_en', models.CharField(max_length=100)),
                ('last_name_en', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria'), ('Nasr City', 'Nasr City'), ('Mansoura', 'Mansoura'), ('Tanta', 'Tanta'), ('Asyut', 'Asyut'), ('Fayoum', 'Fayoum'), ('Zagazig', 'Zagazig'), ('Ismailia', 'Ismailia'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LawsuitCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Case', max_length=255)),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('family', 'Family'), ('labor', 'Labor'), ('commercial', 'Commercial')], default='civil', max_length=50)),
                ('description', models.TextField(default='No description provided.')),
                ('date_filed', models.DateField(default=datetime.timezone)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('verdict', models.TextField(blank=True, null=True)),
                ('verdict_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.court')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lawyer')),
            ],
        ),
    ]
