# Generated by Django 5.2 on 2025-05-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='languages',
            field=models.CharField(default='Arabic, English', max_length=200),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='location',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria'), ('Nasr City', 'Nasr City'), ('Mansoura', 'Mansoura'), ('Tanta', 'Tanta'), ('Asyut', 'Asyut'), ('Fayoum', 'Fayoum'), ('Zagazig', 'Zagazig'), ('Ismailia', 'Ismailia'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan')], default='Cairo', max_length=100),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='specialization',
            field=models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('family', 'Family'), ('labor', 'Labor'), ('commercial', 'Commercial')], default='civil', max_length=50),
        ),
    ]
