# Generated by Django 5.2 on 2025-05-13 17:06

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lawyer_bio_lawyer_consultation_fee_lawyer_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('evidence', 'Evidence'), ('contract', 'Contract'), ('report', 'Report'), ('photo', 'Photo'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=app.models.case_document_path)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.lawsuitcase')),
            ],
        ),
        migrations.CreateModel(
            name='CaseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('plaintiff', 'Plaintiff'), ('defendant', 'Defendant'), ('witness', 'Witness'), ('expert', 'Expert Witness'), ('other', 'Other')], max_length=20)),
                ('contact_info', models.TextField()),
                ('address', models.TextField()),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.lawsuitcase')),
            ],
        ),
    ]
